development:
  database:
    host: localhost
    name: cod2web_dev
  memcached:
    host: localhost
    port: 11211 # default: 11211
test:
  database:
    host: localhost
    name: cod2web_test
  memcached:
    host: localhost
    port: 11211

